#!/bin/sh
# Build iptv-assistant_*.run self-extracting installer for iStoreOS 25.12
# Format: Makeself 2.7.2 compatible (shell header + gzip-compressed tar)
# Output: iptv-assistant_<version>_sdk_25.12_all.run

set -e
cd "$(dirname "$0")"

VERSION="1.1.0"
PKGNAME="iptv-assistant"
ARCH="all"
RUN_NAME="${PKGNAME}_${VERSION}_sdk_25.12_${ARCH}.run"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# Stage files: rootfs/ + install.sh at top level
STAGE="$WORKDIR/$PKGNAME"
mkdir -p "$STAGE"
cp -R rootfs install.sh "$STAGE/"

# Build payload: gzip-compressed tar
PAYLOAD="$WORKDIR/payload.tar.gz"
( cd "$WORKDIR" && tar czf "$PAYLOAD" "$PKGNAME" )

PAYLOAD_SIZE=$(wc -c < "$PAYLOAD")
PAYLOAD_MD5=$(md5 -q "$PAYLOAD" 2>/dev/null || md5sum "$PAYLOAD" | awk '{print $1}')

# Count lines in header (tail -n +N uses 1-indexed line numbers)
HEADER_FILE="$WORKDIR/header.sh"
cat > "$HEADER_FILE" <<EOF
#!/bin/sh
# This is a self-extracting installer generated by iptv-assistant build.sh
# Compatible with iStoreOS 25.12 .run format (Makeself-style)

ORIG_UMASK=\`umask\`
umask 022

CRCsum="0"
MD5="${PAYLOAD_MD5}"
SHA="0000000000000000000000000000000000000000000000000000000000000000"
SIGNATURE=""
TMPROOT=\${TMPDIR:=/tmp}
USER_PWD="\$PWD"
export USER_PWD
ARCHIVE_DIR=\`dirname "\$0"\`
export ARCHIVE_DIR
ARCHIVE_NAME=\`basename "\$0"\`
export ARCHIVE_NAME

label="luci-app-iptv-assistant ${VERSION}"
script="./install.sh"
scriptargs=""
cleanup_script=""
licensetxt=""
helpheader=""
preextract=""
targetdir="${PKGNAME}"
filesizes="${PAYLOAD_SIZE}"
totalsize="${PAYLOAD_SIZE}"
keep="n"
nooverwrite="n"
quiet="n"
accept="n"
nodiskspace="n"
export_conf="n"
decrypt_cmd=""
skip="@@SKIP@@"

print_cmd_arg=""
if type printf > /dev/null; then
    print_cmd="printf"
else
    print_cmd="echo"
fi

unset CDPATH

if [ "\$1" = "--help" ] || [ "\$1" = "-h" ]; then
    echo "iptv-assistant ${VERSION} self-extracting installer"
    echo "Run: sh ${RUN_NAME}"
    echo "Or:  iStore → Manual Install → upload this file"
    exit 0
fi

EXTRACT_DIR="\$TMPROOT/${PKGNAME}.\$\$"
mkdir -p "\$EXTRACT_DIR"

echo "[*] Extracting iptv-assistant ${VERSION} to \$EXTRACT_DIR …"
tail -n +\$skip "\$0" | tar xzf - -C "\$EXTRACT_DIR"

echo "[*] Running installer…"
cd "\$EXTRACT_DIR/${PKGNAME}"
sh ./install.sh
RC=\$?

echo "[*] Cleaning up…"
rm -rf "\$EXTRACT_DIR"
exit \$RC
__PAYLOAD_BELOW__
EOF

# Count lines in header (the __PAYLOAD_BELOW__ line is the last line)
# skip must point at the line containing the gzip stream, which is one past
# the __PAYLOAD_BELOW__ marker line. wc -l counts complete lines; since
# __PAYLOAD_BELOW__ is followed by a newline then the payload, skip = wc -l + 2.
SKIP=$(wc -l < "$HEADER_FILE")
SKIP=$((SKIP + 2))
# Insert actual skip value
sed "s/@@SKIP@@/$SKIP/" "$HEADER_FILE" > "$WORKDIR/header_final.sh"
# Ensure header ends with a newline before binary payload
printf "\n" >> "$WORKDIR/header_final.sh"

# Assemble .run: header + payload
cat "$WORKDIR/header_final.sh" "$PAYLOAD" > "$RUN_NAME"
chmod +x "$RUN_NAME"

echo "Built: $RUN_NAME ($(wc -c < "$RUN_NAME") bytes)"
echo "Payload: $PAYLOAD_SIZE bytes (gzipped tar), MD5: $PAYLOAD_MD5"
echo "Skip line: $SKIP"
